In [1]:
import numpy as np

In [2]:
List=[1,2,3,4,5,6]
print(List)

[1, 2, 3, 4, 5, 6]


In [19]:
Array=np.array(List)
Array

array([1, 2, 3, 4, 5, 6])

In [20]:
a=Array
print(a)

[1 2 3 4 5 6]


In [7]:
x=a+5
print(x)

[ 6  7  8  9 10 11]


In [39]:
b=np.array([6,7,8,9])
c=np.array([2.0,3.0,9.0,5.0])
print(b.dtype)
print(c.dtype)

int32
float64


In [40]:
y=b+c
print(y)

[ 8. 10. 17. 14.]


In [21]:
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.size)
print(a.nbytes)

(6,)
1
4
6
24


In [11]:
d=np.array([(1,2,3),(4,5,6)])
print(d)

[[1 2 3]
 [4 5 6]]


In [12]:
print(d.shape)

(2, 3)


In [15]:
e=np.array([[[1,2,3],[4,5,6]],
            [[9,8,7],[7,6,5]]])
print(e)
print(e.shape)

[[[1 2 3]
  [4 5 6]]

 [[9 8 7]
  [7 6 5]]]
(2, 2, 3)


In [35]:
R=np.array([[1,2,3]])
r=np.repeat(R,5,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [18]:
z=np.zeros((3,3),dtype=np.int16)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
o=np.ones((2,2,3),dtype=np.int16)
print(o)
print(o.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)


In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
F=np.full((3,3),16)
print(F)

[[16 16 16]
 [16 16 16]
 [16 16 16]]


In [23]:
Fl=np.full_like(F,6)
print(Fl)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [21]:
e=np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
f=np.array([[1,2],[5,6],[8,9]])
print(f)
print(f.flatten())

[[1 2]
 [5 6]
 [8 9]]
[1 2 5 6 8 9]


In [27]:
g=np.array([1,2,3])
h=np.array([4,5,6])
print('g-',g)
print('h-',h)

g- [1 2 3]
h- [4 5 6]


In [29]:
print('Horizontal append-',np.hstack((g,h)))
print('Vertical Append-', np.vstack((g,h)))

Horizontal append- [1 2 3 4 5 6]
Vertical Append- [[1 2 3]
 [4 5 6]]


In [24]:
np.random.rand(4,2)

array([[0.48098045, 0.35390505],
       [0.14637922, 0.15749041],
       [0.88668841, 0.40524134],
       [0.6132539 , 0.20428359]])

In [28]:
np.random.randint(-5,15,size=(3,3))

array([[-4,  4,  8],
       [ 7,  2,  6],
       [ 1, 14,  1]])

In [46]:
normal_array=np.random.normal(5,0.5,10)
print(normal_array)

[4.86293822 4.5941769  5.48283201 5.45524328 4.96126993 4.76910748
 4.84603945 4.63570881 5.18484707 4.94492596]


In [9]:
A=np.asarray(List, dtype=np.int16, order=None)
A

array([1, 2, 3, 4, 5, 6], dtype=int16)

In [15]:
i=np.matrix(np.ones((4,4)), dtype=np.int16)
print(i)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
j=np.asarray(i)[1]=10
print(j)
print(i)

10
[[ 1  1  1  1]
 [10 10 10 10]
 [ 1  1  1  1]
 [ 1  1  1  1]]


In [20]:
np.arange(1,30,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [21]:
np.linspace(1.0,10.0,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
np.linspace(1.0,10.0,num=5,endpoint=False)

array([1. , 2.8, 4.6, 6.4, 8.2])

In [25]:
np.linspace(1.0,10.0,num=5,endpoint=True)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
np.logspace(2.0,5.0,num=5)

array([   100.        ,    562.34132519,   3162.27766017,  17782.79410039,
       100000.        ])

In [33]:
k=np.array([1,2,3,5.0])
k.itemsize

8

In [40]:
l=np.array([(1,2,3),(6,7,8),(4,5,9)])
print(l)
print('First row-', l[0])
print('Second row-', l[1])
print('Third row-', l[2])
print('First column- ', l[:,0])
print('Second column- ', l[:,1])
print('Third column-', l[:,2])

[[1 2 3]
 [6 7 8]
 [4 5 9]]
First row- [1 2 3]
Second row- [6 7 8]
Third row- [4 5 9]
First column-  [1 6 4]
Second column-  [2 7 5]
Third column- [3 8 9]


In [45]:
print(l[1,:2]) #2nd row, 2 values
print(l[0:2,2]) #2 value, 3rd colomn

[6 7]
[3 8]


In [48]:
print('min-',np.min(normal_array))
print('max-',np.max(normal_array)) 
print('mean-',np.mean(normal_array))
print('median-',np.median(normal_array))
print('std-',np.std(normal_array))

min- 4.594176902326085
max- 5.482832012915883
mean- 4.973708911012187
median- 4.903932094109964
std- 0.29417073077778955


In [3]:
m=np.array([2,3])
n=np.array([4,5])
np.dot(m,n)

23

In [4]:
m=[[1,2],[3,4]] 
n=[[5,6],[7,8]] 
np.matmul(m,n)

array([[19, 22],
       [43, 50]])

In [8]:
B=np.array([[3,4,6],
            [9,8,1],
            [2,5,3]])
inv_B=np.linalg.inv(B)
print(inv_B)

[[ 0.14503817  0.13740458 -0.33587786]
 [-0.19083969 -0.02290076  0.38931298]
 [ 0.22137405 -0.05343511 -0.09160305]]


In [7]:
det_B=np.linalg.det(B)
print(int(det_B))

131


In [9]:
rank_B=np.linalg.matrix_rank(B)
print(rank_B)

3


In [13]:
p=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [13,14,15,16]])
eigen_values, eigen_vectors=np.linalg.eig(p)
print("Eigen values-",eigen_values)
print("Eigen vectors-",eigen_vectors)

Eigen values- [ 3.62093727e+01 -2.20937271e+00 -2.57831463e-15  5.57979826e-17]
Eigen vectors- [[-0.15115432  0.72704996  0.51747505 -0.06588506]
 [-0.34923733  0.28320876 -0.82375673 -0.31743721]
 [-0.54732033 -0.16063243  0.09508831  0.83252961]
 [-0.74540333 -0.60447363  0.21119337 -0.44920733]]


In [16]:
q=np.matrix('[6, 2; 3, 4]')
diag_q=q.diagonal()
trace_q=q.trace()
print(q)
print("Diagonal-",diag_q)
print("Trace-",trace_q)

[[6 2]
 [3 4]]
Diagonal- [[6 4]]
Trace- [[10]]
